FROM php:7.2-fpm-alpine

LABEL maintainer="StevenLei <shanestevenlei@gmail.com>"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk --no-cache update \
    && apk --no-cache add \
        freetype-dev \
        libmemcached-dev \
        libzip-dev\
        libjpeg-turbo-dev \
        libpng-dev \
        libmcrypt-dev

# Install the PHP pdo_mysql extention
RUN docker-php-ext-install pdo_mysql \
  # Install the PHP gd library
  && docker-php-ext-configure gd \
    --with-freetype-dir=/usr/include/ \
    --with-jpeg-dir=/usr/include/ \
    --with-png-dir=/usr/include/ \
  && docker-php-ext-install gd \
  && rm -rf /var/cache/apk/*