FROM php:7.2-fpm-alpine

LABEL maintainer="StevenLei <shanestevenlei@gmail.com>"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update --no-cache \
    && apk add --no-cache --virtual .build-deps \
        freetype-dev \
        libmemcached-dev \
        libzip-dev\
        libjpeg-turbo-dev \
        libpng-dev \
        libmcrypt-dev

# Install the PHP pdo_mysql extention
RUN docker-php-ext-install pdo_mysql \
  # Install the PHP gd library
  && docker-php-ext-configure gd \
    --with-jpeg-dir=/usr/lib \
    --with-freetype-dir=/usr/include/freetype2 \
  && docker-php-ext-install gd \
  && apk del --no-network .build-deps